// Extracts the real lucide-react icon nodes the app uses into a static map of SVG bodies.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const icons = require
  .resolve("lucide-react/package.json")
  .replace("package.json", "dist/esm/icons/");
const target = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../stage/icons.js",
);

/** Film name → lucide file name (the same icons the dashboard renders). */
const NAMES = {
  sparkles: "sparkles",
  x: "x",
  calendarClock: "calendar-clock",
  usersRound: "users-round",
  gitPullRequest: "git-pull-request",
  gitCommit: "git-commit-horizontal",
  clipboardList: "clipboard-list",
  minus: "minus",
  plus: "plus",
  checkCircle2: "circle-check-big",
  circleCheck: "circle-check",
  home: "house",
  clock: "clock",
  pieChart: "chart-pie",
  trophy: "trophy",
  folder: "folder",
  lightbulb: "lightbulb",
  settings: "settings",
  pause: "pause",
  square: "square",
  search: "search",
  calendarDays: "calendar-days",
  sun: "sun",
  hourglass: "hourglass",
  chevronLeft: "chevron-left",
  chevronRight: "chevron-right",
  send: "send",
  radar: "radar",
  checkSquare: "square-check-big",
  users: "users",
  check: "check",
  xCircle: "circle-x",
  rows3: "rows-3",
  layers: "layers",
  phoneCall: "phone-call",
  bell: "bell",
  shieldCheck: "shield-check",
  moreVertical: "ellipsis-vertical",
  keyboard: "keyboard",
  mic: "mic",
  arrowRight: "arrow-right",
  timerReset: "timer-reset",
  lock: "lock",
  loader: "loader-circle",
  fileText: "file-text",
};

const out = {};
for (const [key, file] of Object.entries(NAMES)) {
  const source = readFileSync(`${icons}${file}.js`, "utf8");
  const match = source.match(/const __iconNode = (\[[\s\S]*?\]);\n/);
  if (!match) throw new Error(`lucide icon node not found: ${file}`);
  // The node is a plain array literal of [tag, attrs] pairs; JSON-ify its unquoted keys to parse it safely.
  const json = match[1].replace(/([{,]\s*)([a-zA-Z][\w-]*)\s*:/g, '$1"$2":');
  const node = JSON.parse(json);
  out[key] = node
    .map(([tag, attrs]) => {
      const props = Object.entries(attrs)
        .filter(([name]) => name !== "key")
        .map(([name, value]) => `${name}="${value}"`)
        .join(" ");
      return `<${tag} ${props}/>`;
    })
    .join("");
}
writeFileSync(
  target,
  `// Generated by scripts/gen-icons.mjs — do not edit.\nwindow.ICONS = ${JSON.stringify(out)};\n`,
);
console.log(`icons.js: ${Object.keys(out).length} icons`);
