/**
 * Commit clustering for the day reconstructor.
 *
 * A day's commits are not a list of tasks — they are the fossil record of a
 * few continuous work sessions. Committing at 09:12, 09:40 and 11:05 is one
 * morning of work, not three lançamentos. This module rebuilds those sessions
 * so "Preencher meu dia" can propose code work with a believable duration and
 * an auditable justification, instead of collapsing everything into whichever
 * pull request happened to be merged that day.
 *
 * Pure and deterministic: same commits in, same sessions out.
 */

import type { NormalizedCommitActivity } from "./engine";

/** Commits farther apart than this belong to different work sessions. */
const SESSION_GAP_MINUTES = 90;
/** Work always starts before the first commit of a session lands. */
const RAMP_UP_MINUTES = 30;
const MIN_SESSION_MINUTES = 30;
const MAX_SESSION_MINUTES = 300;
const GRANULARITY_MINUTES = 15;

/**
 * Merge commits are bookkeeping generated by Azure DevOps or Git, not typed
 * work. They still carry useful work-item links, so they are kept as evidence
 * but never drive a session's duration on their own.
 */
const MERGE_MESSAGE_PATTERN =
  /^(merged?\s+(pull\s+request|pr)\b|merge\s+branch\b|merge\s+remote-tracking\b)/i;

/**
 * A merge lands shortly after the last commit it carries. Wider than that and
 * a pull request starts absorbing sessions it had nothing to do with.
 */
const MERGE_TRAILING_WINDOW_MINUTES = 120;
const MERGE_LEADING_WINDOW_MINUTES = 15;

/** Conventional-commit prefix, stripped so the headline reads as prose. */
const CONVENTIONAL_PREFIX_PATTERN =
  /^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([^)]*\))?!?:\s*/i;

export interface CommitSession {
  /** Stable across rebuilds — derived from the commits themselves. */
  id: string;
  /** Azure DevOps project name, used to match a Time Tracker project. */
  projectName: string;
  repositoryName: string;
  branches: string[];
  commitIds: string[];
  commitCount: number;
  /** Commits excluding merge bookkeeping — what actually drove the estimate. */
  substantiveCount: number;
  workItemIds: number[];
  startIso: string;
  endIso: string;
  /** Estimated effort, already rounded and clamped. */
  minutes: number;
  /** Cleaned-up message of the most representative commit. */
  headline: string;
  /** pt-BR explanation of how `minutes` was arrived at. */
  basis: string;
  /** Link to the first commit, when Azure DevOps returned one. */
  url: string | null;
}

// ─── Helpers ─────────────────────────────────────────────────────────

function toTime(iso: string): number {
  return new Date(iso).getTime();
}

function clampMinutes(minutes: number): number {
  const bounded = Math.min(
    Math.max(minutes, MIN_SESSION_MINUTES),
    MAX_SESSION_MINUTES,
  );
  return Math.round(bounded / GRANULARITY_MINUTES) * GRANULARITY_MINUTES;
}

function isMergeCommit(commit: NormalizedCommitActivity): boolean {
  return MERGE_MESSAGE_PATTERN.test((commit.message ?? "").trim());
}

/** "feat(auth): valida o token" -> "Valida o token". */
export function cleanCommitHeadline(message: string): string {
  const single = message.split("\n")[0] ?? "";
  const stripped = single
    .replace(CONVENTIONAL_PREFIX_PATTERN, "")
    .replace(/\s*\(#\d+\)\s*$/, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!stripped) return "Desenvolvimento";
  return stripped.charAt(0).toUpperCase() + stripped.slice(1);
}

/** HH:mm in the viewer's locale, for the evidence line. */
function formatClock(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";

  return `${String(date.getHours()).padStart(2, "0")}:${String(
    date.getMinutes(),
  ).padStart(2, "0")}`;
}

/**
 * Longest message wins: a one-word "wip" says less about the session than
 * "Corrige cálculo de horas extras no relatório".
 */
function pickHeadline(commits: NormalizedCommitActivity[]): string {
  const best = commits.reduce<NormalizedCommitActivity | null>(
    (winner, commit) => {
      const candidate = cleanCommitHeadline(commit.message ?? "");
      if (candidate === "Desenvolvimento") return winner;

      const current = winner ? cleanCommitHeadline(winner.message ?? "") : "";
      return candidate.length > current.length ? commit : winner;
    },
    null,
  );

  return cleanCommitHeadline(best?.message ?? "");
}

/** Splits a repository's chronological commits on idle gaps. */
function splitOnGaps(
  commits: NormalizedCommitActivity[],
): NormalizedCommitActivity[][] {
  const groups: NormalizedCommitActivity[][] = [];
  let current: NormalizedCommitActivity[] = [];

  for (const commit of commits) {
    const previous = current.at(-1);

    if (previous) {
      const gap = Math.abs(
        toTime(commit.timestamp) - toTime(previous.timestamp),
      );
      if (gap / 60_000 > SESSION_GAP_MINUTES) {
        groups.push(current);
        current = [];
      }
    }

    current.push(commit);
  }

  if (current.length > 0) groups.push(current);
  return groups;
}

function buildSession(
  commits: NormalizedCommitActivity[],
): CommitSession | null {
  const first = commits[0];
  const last = commits.at(-1);
  if (!first || !last) return null;

  // Merge commits inflate a session without representing typed work: a PR
  // merged at 18:00 would stretch a morning session across the whole day.
  const substantive = commits.filter((commit) => !isMergeCommit(commit));
  if (substantive.length === 0) return null;

  const spanStart = substantive[0] ?? first;
  const spanEnd = substantive.at(-1) ?? last;
  const spanMinutes = Math.max(
    0,
    Math.round(
      (toTime(spanEnd.timestamp) - toTime(spanStart.timestamp)) / 60_000,
    ),
  );

  const minutes = clampMinutes(spanMinutes + RAMP_UP_MINUTES);
  const workItemIds = [
    ...new Set(commits.flatMap((commit) => commit.workItemIds)),
  ];
  const branches = [
    ...new Set(
      commits
        .map((commit) => commit.branch)
        .filter((branch): branch is string => Boolean(branch)),
    ),
  ];

  const startClock = formatClock(spanStart.timestamp);
  const endClock = formatClock(spanEnd.timestamp);

  const basis =
    substantive.length === 1
      ? `Estimado a partir de 1 commit às ${startClock}, com ${RAMP_UP_MINUTES}min de preparação.`
      : `Estimado pela janela de ${startClock} a ${endClock} (${substantive.length} commits), + ${RAMP_UP_MINUTES}min de preparação.`;

  return {
    id: `commits:${first.repositoryName}:${first.commitId}`,
    projectName: first.projectName,
    repositoryName: first.repositoryName,
    branches,
    commitIds: commits.map((commit) => commit.commitId),
    commitCount: commits.length,
    substantiveCount: substantive.length,
    workItemIds,
    startIso: spanStart.timestamp,
    endIso: spanEnd.timestamp,
    minutes,
    headline: pickHeadline(substantive),
    basis,
    url: first.url ?? null,
  };
}

// ─── Pull-request attribution ────────────────────────────────────────

/** The fields the matcher needs from a pull request. */
export interface PullRequestForMatching {
  id: number;
  repositoryName: string;
  sourceBranch: string | null;
  workItemIds: number[];
  closedAt: string | null;
}

/** "refs/heads/feature/x" -> "feature/x" */
function stripRefPrefix(ref: string | null): string | null {
  if (!ref) return null;
  return ref.replace(/^refs\/heads\//, "").trim() || null;
}

/**
 * Sessions a pull request plausibly produced.
 *
 * Deliberately narrow. The naive alternative — "every commit in the repo that
 * day" — makes a single PR swallow an entire workday of unrelated sessions,
 * which is exactly how a day of three distinct efforts collapses into one
 * eight-hour line.
 */
export function sessionsForPullRequest(
  sessions: CommitSession[],
  pullRequest: PullRequestForMatching,
): CommitSession[] {
  const repository = pullRequest.repositoryName.trim().toLowerCase();
  const branch =
    stripRefPrefix(pullRequest.sourceBranch)?.toLowerCase() ?? null;
  const workItems = new Set(pullRequest.workItemIds);
  const closedAt = pullRequest.closedAt
    ? new Date(pullRequest.closedAt).getTime()
    : Number.NaN;

  return sessions.filter((session) => {
    if (session.repositoryName.trim().toLowerCase() !== repository)
      return false;

    // Strongest: the work item links the two explicitly.
    if (session.workItemIds.some((id) => workItems.has(id))) return true;

    // Branch names are parsed out of commit messages, so a hit is meaningful
    // but a miss proves nothing.
    if (
      branch &&
      session.branches.some((candidate) => candidate.toLowerCase() === branch)
    ) {
      return true;
    }

    // Last resort: the merge happened right after this session ended.
    if (Number.isNaN(closedAt)) return false;

    const start =
      toTime(session.startIso) - MERGE_LEADING_WINDOW_MINUTES * 60_000;
    const end = toTime(session.endIso) + MERGE_TRAILING_WINDOW_MINUTES * 60_000;
    return closedAt >= start && closedAt <= end;
  });
}

/**
 * Effort implied by a set of sessions — the sum of real work windows, never
 * the span between the first and the last, which would bill the lunch break
 * and the evening gap along with the code.
 */
export function estimateFromSessions(
  sessions: CommitSession[],
): { minutes: number; basis: string } | null {
  if (sessions.length === 0) return null;

  const minutes = sessions.reduce((sum, session) => sum + session.minutes, 0);
  const commits = sessions.reduce(
    (sum, session) => sum + session.substantiveCount,
    0,
  );

  return {
    minutes,
    basis:
      sessions.length === 1
        ? (sessions[0]?.basis ?? "Estimado pelos commits do dia.")
        : `Soma de ${sessions.length} blocos de trabalho (${commits} commits), com ${RAMP_UP_MINUTES}min de preparação cada.`,
  };
}

// ─── Engine ──────────────────────────────────────────────────────────

/**
 * Groups commits into work sessions, one bucket per repository so the evidence
 * stays coherent, then split wherever the developer went idle.
 *
 * Returned longest-first: when a plan has room for only some of them, the
 * heaviest sessions are the ones worth proposing.
 */
export function buildCommitSessions(
  commits: NormalizedCommitActivity[],
): CommitSession[] {
  const byRepository = new Map<string, NormalizedCommitActivity[]>();

  for (const commit of commits) {
    if (Number.isNaN(toTime(commit.timestamp))) continue;

    const key = `${commit.projectName} ${commit.repositoryName}`;
    const bucket = byRepository.get(key) ?? [];
    bucket.push(commit);
    byRepository.set(key, bucket);
  }

  const sessions: CommitSession[] = [];

  for (const bucket of byRepository.values()) {
    const chronological = [...bucket].sort(
      (a, b) => toTime(a.timestamp) - toTime(b.timestamp),
    );

    for (const group of splitOnGaps(chronological)) {
      const session = buildSession(group);
      if (session) sessions.push(session);
    }
  }

  return sessions.sort(
    (a, b) => b.minutes - a.minutes || a.startIso.localeCompare(b.startIso),
  );
}
