import { getAppTimeZone } from "@/lib/timezone";
import type { TeamCallSignal } from "@/types/collaboration";

/** Shared by review surfaces and duplicate detection; never generated by AI. */
export function describeTeamCall(call: TeamCallSignal): string {
  if (call.description) return call.description;
  const time = new Intl.DateTimeFormat("pt-BR", {
    timeZone: getAppTimeZone(),
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).format(new Date(call.startIso));
  const name =
    call.callType === "groupCall" ? "em grupo" : call.otherParticipantName;
  return `Chamada Teams: ${name.replace(/\s+/g, " ").trim().slice(0, 120)} (${time})`;
}

type Interval = { start: number; end: number };

function subtract(intervals: Interval[], blocker: Interval): Interval[] {
  return intervals.flatMap((interval) => {
    if (blocker.end <= interval.start || blocker.start >= interval.end)
      return [interval];
    const remaining: Interval[] = [];
    if (blocker.start > interval.start)
      remaining.push({ start: interval.start, end: blocker.start });
    if (blocker.end < interval.end)
      remaining.push({ start: blocker.end, end: interval.end });
    return remaining;
  });
}

/** Only non-overlapping, unlogged participation becomes a new suggestion. */
export function buildDayCallSignals(input: {
  calls: TeamCallSignal[];
  date: string;
  startIso: string;
  endIso: string;
  calendar: Array<{ startIso: string; endIso: string }>;
  existingDescriptions: string[];
  acceptedCallIds?: ReadonlySet<string>;
  keepLogged?: boolean;
}): TeamCallSignal[] {
  const start = Date.parse(input.startIso);
  const end = Date.parse(input.endIso);
  const occupied = input.calendar
    .map((event) => ({
      start: Date.parse(event.startIso),
      end: Date.parse(event.endIso),
    }))
    .filter(
      (interval) =>
        Number.isFinite(interval.start) && interval.end > interval.start,
    );
  const descriptions = new Set(
    input.existingDescriptions.map((value) =>
      value.trim().toLowerCase().replace(/\s+/g, " "),
    ),
  );
  const seen = new Set<string>();
  const result: TeamCallSignal[] = [];
  for (const call of [...input.calls].sort(
    (a, b) => a.startIso.localeCompare(b.startIso) || a.id.localeCompare(b.id),
  )) {
    if (seen.has(call.id)) continue;
    seen.add(call.id);
    // Missing session intervals must never turn a global call span into measured work.
    let intervals = (call.intervals ?? [])
      .map((interval) => ({
        start: Math.max(start, Date.parse(interval.startIso)),
        end: Math.min(end, Date.parse(interval.endIso)),
      }))
      .filter(
        (interval) =>
          Number.isFinite(interval.start) && interval.end > interval.start,
      );
    const originalMs = intervals.reduce(
      (sum, interval) => sum + interval.end - interval.start,
      0,
    );
    for (const blocker of occupied) intervals = subtract(intervals, blocker);
    // Also defend against overlapping intervals in an upstream record.
    const unique: Interval[] = [];
    for (const interval of intervals) {
      let pieces = [interval];
      for (const blocker of unique) pieces = subtract(pieces, blocker);
      unique.push(...pieces);
    }
    unique.sort((a, b) => a.start - b.start);
    const totalMs = unique.reduce(
      (sum, interval) => sum + interval.end - interval.start,
      0,
    );
    if (totalMs < 60_000) continue;
    occupied.push(...unique);
    const signal: TeamCallSignal = {
      ...call,
      id: `${call.id}:${input.date}`,
      date: input.date,
      startIso: new Date(unique[0].start).toISOString(),
      endIso: new Date(unique[unique.length - 1].end).toISOString(),
      minutes: Math.floor(totalMs / 60_000),
      intervals: unique.map((interval) => ({
        startIso: new Date(interval.start).toISOString(),
        endIso: new Date(interval.end).toISOString(),
      })),
      wasClipped: totalMs < originalMs,
    };
    signal.description = describeTeamCall(signal);
    signal.alreadyLogged =
      Boolean(input.acceptedCallIds?.has(signal.id)) ||
      descriptions.has(signal.description.toLowerCase());
    if (input.keepLogged || !signal.alreadyLogged) result.push(signal);
  }
  return result;
}
